### ISSUE TITLE
Workspace is empty when returing from another workspace

### ISSUE THREAD

**Issue by RJDan** [miracle-wm-org/miracle-wm#512]
When I switch back to a workspace which had apps/windows open, the workspace is almost always 'empty'.
When I open a new app, some of the windows reappear. Other windows remain 'disappeared' but the space they would occupy on screen still exists but is empty.

This has made it impossible to use miraclewm for anything other than testing miraclewm.

OS: Ubuntu 24.04.2 LTS x86_64 
Host: ASUS TUF Gaming A15 FA506IH_FA506IH 1.0 
Kernel: 6.8.0-60-generic 
Uptime: 48 mins 
Packages: 3312 (dpkg), 28 (flatpak), 127 (snap) 
Shell: bash 5.2.21 
Resolution: 1920x1080 
DE: miracle-wm-snap 
WM: sway 
Terminal: kitty 
CPU: AMD Ryzen 7 4800H with Radeon Graphics (16) @ 2.900GHz 
GPU: AMD ATI Radeon RX Vega 6 
GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q 
Memory: 5924MiB / 39524MiB

snap-id:      feeK3fEyb12CsWiHDArUvU15Mr3PweFb
tracking:     latest/edge
refresh-date: yesterday at 08:34 CEST
channels:
installed:          v0.5.2-34-g7d1f112            (771) 60MB classic

**Comment by mattkae** [comment]
This should be fixed on latest, let me know!

**Comment by RJDan** [comment]
Hello
Issue still happens on my desktop.
I have not checked on my laptop yet.

snap-id:      feeK3fEyb12CsWiHDArUvU15Mr3PweFb
tracking:     latest/stable
refresh-date: 5 days ago, at 10:37 CEST
channels:
  latest/stable:    v0.6.2             2025-07-16 (913) 60MB classic
  latest/candidate: 0.3.0              2024-07-01 (227) 59MB classic
  latest/beta:      ↑                                        
  latest/edge:      v0.6.2-13-g7b92a95 2025-07-17 (919) 60MB classic
installed:          v0.6.2                        (913) 60MB classic

OS: Ubuntu 24.04.2 LTS x86_64 
Host: OptiPlex 7050 
Kernel: 6.8.0-64-generic 
Uptime: 8 mins 
Packages: 2597 (dpkg), 14 (flatpak), 110 (snap) 
Shell: bash 5.2.21 
Resolution: 2560x1440 
DE: miracle-wm-snap 
WM: sway 
Terminal: kitty 
CPU: Intel i5-7600 (4) @ 4.100GHz 
GPU: Intel HD Graphics 630 
GPU: AMD ATI Radeon HD 8830M / R7 250 / R7 M465X 
Memory: 5369MiB / 31958MiB

**Comment by RJDan** [comment]
Still an issue with my laptop.
snap-id:      feeK3fEyb12CsWiHDArUvU15Mr3PweFb
tracking:     latest/edge
refresh-date: 4 days ago, at 13:39 CEST
channels:
  latest/stable:    v0.6.2             2025-07-16 (913) 60MB classic
  latest/candidate: 0.3.0              2024-07-01 (227) 59MB classic
  latest/beta:      ↑                                        
  latest/edge:      v0.6.2-13-g7b92a95 2025-07-17 (919) 60MB classic
installed:          v0.6.2-13-g7b92a95            (919) 60MB classic

OS: Ubuntu 25.04 x86_64 
Host: ASUS TUF Gaming A15 FA506IH_FA506IH 1.0 
Kernel: 6.14.0-24-generic 
Uptime: 11 mins 
Packages: 3468 (dpkg), 27 (flatpak), 132 (snap) 
Shell: bash 5.2.37 
Resolution: 1920x1080 
DE: miracle-wm-snap 
WM: sway 
Terminal: kitty 
CPU: AMD Ryzen 7 4800H with Radeon Graphics (16) @ 2.90 
GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q 
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Se 
Memory: 6848MiB / 38499MiB

**Comment by mattkae** [comment]
I believe that I fixed this once and for all by now, but lmk if it's not!
